import React,{useMemo,useState,useEffect}from'react';import{createRoot}from'react-dom/client';import{Printer,RotateCcw,Palette,FileText}from'lucide-react';import'./styles.css';
const sample={name:'Prénom NOM',title:'Commerciale B2B',email:'email@example.com',phone:'+33 0 00 00 00 00',city:'Île-de-France',profile:"Commerciale orientée développement et fidélisation, avec une expérience en vente B2B, gestion de comptes clients, appels d'offres et outils CRM. Organisée, autonome et dotée d'un excellent relationnel.",skills:'Prospection multicanale\nNégociation commerciale\nGestion du cycle de vente\nFidélisation client\nRéponse aux appels d’offres\nCRM, Excel, Office',experiences:'Commerciale | Entreprise A | 2024 – 2025 | Paris | Prospection client, fidélisation, propositions commerciales, négociation, suivi des contrats et gestion CRM.\nAssistante commerciale | Entreprise B | 2019 – 2022 | Nanterre | Renouvellement de contrats, ventes additionnelles, gestion de base de données, relances et coordination administrative.\nEmployée administrative | Entreprise C | 2017 – 2018 | Paris | Assistance client, gestion des litiges et suivi administratif.',education:'Master Négociation Commerciale Internationale | Université | 2014 | Paris\nLicence LEA Anglais-Allemand | Université | 2013 | Paris\nBTS Commerce International | Lycée | 2011 | Île-de-France',languages:'Français langue maternelle\nAnglais courant\nAllemand notions professionnelles',interests:'Théâtre\nSport\nEngagement associatif',template:'premium',accent:'#123047',soft:'#eaf0f4'};
const templates=[['premium','Premium'],['sidebar','Sidebar'],['minimal','Minimal'],['timeline','Timeline'],['cards','Cartes'],['lux','Luxe']];
const lines=v=>v.split('\n').map(x=>x.trim()).filter(Boolean);const parseRows=v=>lines(v).map(x=>{const p=x.split('|').map(s=>s.trim());return{a:p[0]||'',b:p[1]||'',c:p[2]||'',d:p[3]||'',e:p.slice(4).join(' | ')||''}});
function Field({label,value,onChange,area}){return <label className="field"><span>{label}</span>{area?<textarea value={value} onChange={e=>onChange(e.target.value)} rows={area}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function Editor({cv,setCv}){const set=(k,v)=>setCv({...cv,[k]:v});return <aside className="editor"><div className="logo"><b>CV Studio</b><small>MVP live editor</small></div><div className="block"><h3><Palette size={16}/> Design</h3><select value={cv.template} onChange={e=>set('template',e.target.value)}>{templates.map(t=><option key={t[0]} value={t[0]}>{t[1]}</option>)}</select><Field label="Couleur principale" value={cv.accent} onChange={v=>set('accent',v)}/><Field label="Couleur douce" value={cv.soft} onChange={v=>set('soft',v)}/></div><div className="block"><h3><FileText size={16}/> Contenu</h3><Field label="Nom" value={cv.name} onChange={v=>set('name',v)}/><Field label="Titre" value={cv.title} onChange={v=>set('title',v)}/><Field label="Email" value={cv.email} onChange={v=>set('email',v)}/><Field label="Téléphone" value={cv.phone} onChange={v=>set('phone',v)}/><Field label="Ville" value={cv.city} onChange={v=>set('city',v)}/><Field label="Profil" value={cv.profile} onChange={v=>set('profile',v)} area={5}/><Field label="Compétences" value={cv.skills} onChange={v=>set('skills',v)} area={6}/><Field label="Expériences" value={cv.experiences} onChange={v=>set('experiences',v)} area={8}/><Field label="Formation" value={cv.education} onChange={v=>set('education',v)} area={5}/><Field label="Langues" value={cv.languages} onChange={v=>set('languages',v)} area={4}/><Field label="Intérêts" value={cv.interests} onChange={v=>set('interests',v)} area={3}/></div><div className="buttons"><button onClick={()=>window.print()}><Printer size={16}/> PDF</button><button className="ghost" onClick={()=>setCv(sample)}><RotateCcw size={16}/> Reset</button></div></aside>}
function Header({cv}){return <><h1>{cv.name}</h1><p className="role">{cv.title}</p><p className="contact">{cv.email} · {cv.phone} · {cv.city}</p></>}
function Sections({cv,timeline=false}){const ex=parseRows(cv.experiences),ed=parseRows(cv.education);return <>{!timeline&&<><h2>Profil</h2><p>{cv.profile}</p></>}<h2>Expériences</h2>{ex.map((e,i)=><div className={timeline?'time item':'item'} key={i}><b>{timeline?e.c:e.a+' — '+e.b}</b>{timeline&&<h3>{e.a} — {e.b}</h3>}<small>{timeline?e.d:e.c+' · '+e.d}</small><p>{e.e}</p></div>)}<h2>Compétences</h2><div className="tags">{lines(cv.skills).map(s=><span key={s}>{s}</span>)}</div><h2>Formation</h2>{ed.map((e,i)=><div className="item" key={i}><b>{e.a}</b><small>{e.b} · {e.c} · {e.d}</small></div>)}</>}
function Side({cv}){return <aside className="cvside"><h2>Contact</h2><p>{cv.email}<br/>{cv.phone}<br/>{cv.city}</p><h2>Langues</h2>{lines(cv.languages).map(x=><p key={x}>{x}</p>)}<h2>Intérêts</h2>{lines(cv.interests).map(x=><p key={x}>{x}</p>)}</aside>}
function Preview({cv}){const style={'--accent':cv.accent,'--soft':cv.soft};let body;if(cv.template==='sidebar')body=<div className="layout"><Side cv={cv}/><main><Header cv={cv}/><Sections cv={cv}/></main></div>;else if(cv.template==='timeline')body=<main><Header cv={cv}/><h2>Profil</h2><p>{cv.profile}</p><Sections cv={cv} timeline/></main>;else if(cv.template==='cards')body=<main className="carded"><section><Header cv={cv}/></section><section><h2>Profil</h2><p>{cv.profile}</p></section><section><Sections cv={cv}/></section></main>;else body=<main><Header cv={cv}/><Sections cv={cv}/></main>;return <section className={'paper '+cv.template} style={style}>{body}</section>}
function App(){const[cv,setCv]=useState(()=>JSON.parse(localStorage.getItem('cv-studio')||'null')||sample);useEffect(()=>localStorage.setItem('cv-studio',JSON.stringify(cv)),[cv]);return <div className="app"><Editor cv={cv} setCv={setCv}/><main className="stage"><div className="topbar"><b>Aperçu direct</b><span>{templates.find(t=>t[0]===cv.template)?.[1]}</span></div><Preview cv={cv}/></main></div>}
createRoot(document.getElementById('root')).render(<App/>);